### ISSUE TITLE
getSupportFragmentManager() on a null object reference

### ISSUE THREAD

**Issue by ObidosDev** [callstack/react-native-viewpager#174]
# Bug report
## Summary

Android crash
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'getSupportFragmentManager()' on a null object reference
com.reactnative.community.viewpager2.adapter.FragmentStateAdapter.<init> (FragmentStateAdapter.java:103)

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 49.84 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.2.0 - ~/.nvm/versions/node/v12.2.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v12.2.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.13.1 => 16.13.1 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: 4.0.0

## Steps to reproduce

Crash from Crashlytics 

Describe what you expected to happen:

No crash

## Reproducible sample code

(Common usage)

**Comment by troZee** [comment]
Hey 👋 
Could you check your issue on 3.3.0 ?

**Comment by ObidosDev** [comment]
Sure, I have prepared release with 3.3.0.
but I think `com.reactnative.community.viewpager2.adapter.FragmentStateAdapter.` **viewpager2** was added in 4.0.0

**Comment by ObidosDev** [comment]
Maybe it could help to understand
![Screenshot 2020-05-19 at 14 28 42](https://user-images.githubusercontent.com/16224235/82321170-19545200-99dd-11ea-8c4c-f0f0cc2d2315.png)

**Comment by troZee** [comment]
> I have prepared release with 3.3.0

As you can see https://github.com/react-native-community/react-native-viewpager#versions 
* 3.3.0 contains "old" version of VP
* 4.0.0 contains newer version of VP

Which version causes above issue ?

**Comment by ObidosDev** [comment]
@troZee `Environment info
"@react-native-community/viewpager": "^4.0.0",`
From issue info :)
And now I will try with 3.3.0

**Comment by Bardiamist** [comment]
Couple users got that crash.
"@react-native-community/viewpager": "4.1.4"

https://sentry.io/share/issue/21e4238f8c744600a23e654bef42f06f/
Device: WAS-LX2
Android: 8.0.0

https://sentry.io/share/issue/5a08bd96832c46c88b2f9fdee3e52e20/
Device: MAX_2
Android: 9

**Comment by ZeroJian** [comment]
same problem
@react-native-community/viewpager": "^4.0.1"

like this:
https://sentry.io/share/issue/c8bae7c02dc74e6f87270a02d797f389/

**Comment by teofanes-moreira-tiffin-foods** [comment]
@troZee any updates about that issue? some users getting this crash yet, all in background state.
version `"@react-native-community/viewpager": "4.1.6"`

**Comment by troZee** [comment]
The ViewPager has been reverted to a stable version in 4.2, so you can try this version.

**Comment by ObidosDev** [comment]
@troZee gonna try it, thanks for notification

**Comment by arekkubaczkowski** [comment]
@ObidosDev  I tried to reproduce it on 5.x version and couldn't make appears this error. Could you please provide more details about it?
