### ISSUE TITLE
Crashed when it's builded into APK

### ISSUE THREAD

**Issue by ashirogisen** [callstack/react-native-viewpager#178]
When I open the screen that contains ViewPager components, the app is closed immediately. Anyone know the cause? It works perfectly fine in emulator tho.

RN Version: 
**react-native: 0.61.4**

**Comment by troZee** [comment]
Could you provide a stack trace ? 
What is version of VP ?

**Comment by ashirogisen** [comment]
Thanks for the response.
Btw, where I can get the stack trace? I'm kinda new
for VP, it's **^4.0.0**

**Comment by troZee** [comment]
Can you try build apk for 3.3.0 ? 

If you have release mode, you cannot debug it. You need to use 3rd party lib like crashlytics or write own simple implementation to check the stacktrace. 

If you run your app on phone you can connect to you phone using adb. More you can find here:
https://www.xda-developers.com/quickly-install-adb/
