### ISSUE TITLE
How to render Viewpager as an item in Flatlist

### ISSUE THREAD

**Issue by beingArkReal** [callstack/react-native-viewpager#179]
I'm looking for a way to implement viewpager inside flatlist render as an item, but unfortunately, view pager doesn't show inside a flatlist.

**Comment by troZee** [comment]
Can you provide a code snippet ? 
Probably View Pager has not got defined height, so you need to pass it in styles.

**Comment by NicolayS** [comment]
Hello! I'm sorry, that I interrupt, for me even I wrap up VeiwPager by <View> using the example from this page https://github.com/react-native-community/react-native-viewpager, it doesn't work
below the code
--------MainScreen.js
import React from 'react';
import {
  View,
  Text,
  FlatList,
  Button,
  Platform,
  StyleSheet
} from 'react-native';
import ViewPager from '@react-native-community/viewpager';

const MainScreen = props => {

  return(
      <View>
           <ViewPager style={styles.viewPager} initialPage={0}>
                <View key="1">
                   <Text>First page</Text>
                </View>
                <View key="2">
                   <Text>Second page</Text>
                </View>
             </ViewPager>
    </View>
  );
};

const styles = StyleSheet.create({
  viewPager: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center'
  }
});

export default MainScreen;

**Comment by NicolayS** [comment]
I'm sorry for bothering, adding <View style={{height: 80}} > works perfect

**Comment by beingArkReal** [comment]
> Can you provide a code snippet ?
> Probably View Pager has not got defined height, so you need to pass it in styles.



> Can you provide a code snippet ?
> Probably View Pager has not got defined height, so you need to pass it in styles.



> Can you provide a code snippet ?
> Probably View Pager has not got defined height, so you need to pass it in styles.

Here is the link to what I'm actually trying to pull off 👍 

https://github.com/beingArkReal/view_pager_flatlist/blob/master/index.js


**Note**
_Currently, I'm not able to scroll the FlatList inside the View Pager_

**Comment by AKaiYi** [comment]
https://github.com/beingArkReal/view_pager_flatlist/blob/master/index.js，in 96 lines，is FlatList data DATA_ONE ，Why can only display 10？
