### ISSUE TITLE
Child view disappears, when Fast refresh is enabled

### ISSUE THREAD

**Issue by skychx** [callstack/react-native-viewpager#222]
# Bug report

## Summary

After android Class Component fast refresh, the children Component disappeared

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS Mojave 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 30.50 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 13.12.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 26, 28, 29
      Build Tools: 26.0.3, 28.0.3, 29.0.2, 29.0.3
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
    Python: 2.7.10 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 4.1.6

## Steps to reproduce

```jsx
import React, { PureComponent }  from 'react';
import {StyleSheet, View, Text} from 'react-native';
import ViewPager from '@react-native-community/viewpager';

class ClassApp extends PureComponent {
  render() {
    return (
      <ViewPager style={styles.viewPager} initialPage={0}>
        <View key="1">
          <Text style={styles.viewPagerText}>First page</Text>
        </View>
        <View key="2">
          <Text style={styles.viewPagerText}>Second page</Text>
        </View>
      </ViewPager>
    )
  }
}

const styles = StyleSheet.create({
  viewPager: {
    flex: 1,
  },
  viewPagerText: {
    fontSize: 50,
    textAlign: 'center',
  }
});
```

1. Don’t make any changes, save the code, fast refresh
2. children Component disappeared

<img src="https://user-images.githubusercontent.com/24872439/91524150-1698bf80-e931-11ea-901d-f1e9be4986de.gif" width="30%"/>

**When I use Function Component，everything is OK**

**Comment by skychx** [comment]
### Before Fash Refreshing:

<img src="https://user-images.githubusercontent.com/24872439/91527519-81012e00-e938-11ea-9fe8-f6153f4f0e1b.png" width="100%">

<br />

### After Fash Refreshing:

![image](https://user-images.githubusercontent.com/24872439/91527644-b9087100-e938-11ea-9828-ed74c56e599a.png)

**Comment by skychx** [comment]
@react-native-community/viewpager `4.1.4` have the same problem

**Comment by DKbyo** [comment]
Just for the record, I was using react-native 0.61.5 and got a blocking issue `Module hmr client is not a registered callable module` that it seems related to hot reloading, So, after saw 4.x has some issues related with fast refresh I decided to downgrade to 3.3.1 and everything is working again.

**Comment by Simon-44** [comment]
I had the same problem, I downgraded too and it works.

**Comment by arekkubaczkowski** [comment]
@skychx couldn't reproduce it on 5.x version, could you please check it as well?

**Comment by franklin-vidal** [comment]
Wipe android emulator solves my problem.
