### ISSUE TITLE
Use ViewPager2 dep from maven, instead of fork from github

### ISSUE THREAD

**Issue by grahammendick** [callstack/react-native-viewpager#225]
cc @troZee

Thanks, your project helped me add `ViewPager2` (for RTL support) to the [TabBar component of my navigation library for React Native](https://grahammendick.github.io/navigation/documentation/native/tab-bar.html). So here I am returning the favour.

When you changed to `ViewPager2` you copied the `ViewPager2` source code into your own repository. This was to work around an [issue where the page didn’t update](https://github.com/react-native-community/react-native-viewpager/pull/139#issuecomment-581127077). You don’t need this workaround because you can use the unmodified `ViewPager2` from android. To fix the issue you do a [layout and measure when setting the current item](https://github.com/grahammendick/navigation/blob/2800d42c36bb711819c423de93e7167581c21777/NavigationReactNative/src/android/src/main/java/com/navigation/reactnative/TabBarPagerRTLManager.java#L126)

**Comment by troZee** [comment]
@grahammendick 
Thank you for a feedback. I will convert your topic into feature request, bc it would be nice to use official version of library instead of my fork.

**Comment by troZee** [comment]
So what should be done in this issue: 
- change `implementation 'com.github.troZee:ViewPager2:v1.0.6'` to `implementation "androidx.viewpager2:viewpager2:1.0.0"`
- Apply [this fix](https://github.com/grahammendick/navigation/blob/2800d42c36bb711819c423de93e7167581c21777/NavigationReactNative/src/android/src/main/java/com/navigation/reactnative/TabBarPagerRTLManager.java#L126)
