### ISSUE TITLE
Couldn't find a navigation context

### ISSUE THREAD

**Issue by AleeeKoi** [callstack/react-native-viewpager#226]
Hello!
All works fine except for the assignment of the ref property.
If I create a reference in my functional component like this:

```const viewPageRef = React.useRef()```

an passing to the ViewPage component:

```
<ViewPager ref={viewPageRef} style={styles.viewPager} initialPage={0} >
  {pages.map((Comp, i) => (<Comp key={`main-page-view-${i}`} />))}
</ViewPager>
```

I got the following error:

```Couldn't find a navigation context. Have you wrapped your app with 'NavigationContainer'? See https://reactnavigation.org/docs/getting-started for setup instructions.```

and yes, my app is wrapped in NavigationContainer. I'm using react-navigation v5.

I'm forgetting something?

Thank you

**Comment by troZee** [comment]
Could you compare with our example ? In the example we are also using rn v5

https://github.com/callstack/react-native-viewpager/blob/master/example/src/App.tsx

**Comment by YogiHa** [comment]
Same to me on `Video` component (react-native-video npm).

On ref usage, exactly the same error. 

Looked on @troZee link, and on nested navigator docs (I'm creating Video component called by few nested screens), and looks like I did everything correctly. one `NavigationContainer` parent holds many `.Navigator` screens
