### ISSUE TITLE
Paging broken and some page no rendered with drawer navigation

### ISSUE THREAD

**Issue by tree1891** [callstack/react-native-viewpager#232]
If go forward and back by drawer navigation, viewpager's paging is broken and some pages are not rendered.
react-native-viewpager: 3.3.1, 4.1.16

System:
    OS: Windows 10 10.0.18363
  Binaries:
    Node: 12.16.3
    Yarn: 1.22.4
    npm: 6.14.4
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 25.0.3, 26.0.3, 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-25 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  Languages:
    Java: 1.8.0_231
    Python: 3.7.4
  npmPackages:
    @react-native-community/cli: Not Found
    react: ~16.11.0 => 16.11.0
    react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by infothien** [comment]
I got the same issue on with android, IOS is working fine. Is there any solution for it :(

**Comment by infothien** [comment]
@tree1891 sorry, did you figure out how to deal with it

**Comment by Simon-44** [comment]
Hello,

Same problem, downgrading to 3.3.1 "fixed" this.
