### ISSUE TITLE
ViewPager setPage method does not work on Android

### ISSUE THREAD

**Issue by kim791** [callstack/react-native-viewpager#240]
## Environment

{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/viewpager": "^4.2.0",
    "@react-native-picker/picker": "^1.8.3",
    "@react-navigation/drawer": "^5.10.0",
    "@react-navigation/native": "^5.8.0",
    "@react-navigation/stack": "^5.10.0",
    "@use-expo/font": "^2.0.0",
    "expo": "~39.0.2",
    "expo-font": "~8.3.0",
    "expo-fontawesome": "^0.1.2",
    "expo-splash-screen": "~0.6.1",
    "expo-status-bar": "~1.0.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz",
    "react-native-gesture-handler": "~1.7.0",
    "react-native-navigation": "^7.2.0",
    "react-native-paper": "^4.2.0",
    "react-native-reanimated": "~1.13.0",
    "react-native-router-flux": "^4.2.0",
    "react-native-safe-area-context": "3.1.4",
    "react-native-screens": "~2.10.1",
    "react-native-text-gradient": "^0.1.7",
    "react-native-web": "~0.13.12",
    "react-navigation": "^4.4.2"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0"
  },
  "private": true
}

Testing using Android - Pixel 3A_using Android 11

## Description

I implemented a function call on button click to move to next page using ViewPager. The function works for iOS but does not work for Android 11.0. 

## Reproducible Demo

Code sample: (Fragment)

 ```
import { Button } from "react-native-paper";
import ViewPager from "@react-native-community/viewpager";
import { StyleSheet, View, Text, TouchableOpacity } from "react-native";

function NewAccountScreen(props){

render(

const me = React.createRef();

 <ViewPager
          style={styles.container}
          initialPage={0}
          showPageIndicator="true"
          ref={me}
        >
      <View key = "1"> 
                 <Button
                  icon="chevron-double-right"
                  mode="contained"
                  onPress={() => me.current.setPage("1")}
                  selectedColor={colors.appNavigationBar}
                  color={colors.badgeOn}
                  style={{ borderRadius: 20 }}
                >
                  Next
                </Button>
     </View>
    <View key = "2>Second Page</View>  

); {/** End of render() */}
```

**Comment by troZee** [comment]
https://github.com/callstack/react-native-viewpager/blob/master/example/ViewPagerExample.js#L110

Pass number instead of string. Have you got a typing sytem inside the project ?

**Comment by rewdt** [comment]
I'm experienceing the same issue at the moment. The ios ref.current.setPage() works as intended on android however, there is a delay and after a lot of  presses it starts moving between pages
