### ISSUE TITLE
Default scroll offset  

### ISSUE THREAD

**Issue by lishuo0710** [callstack/react-native-viewpager#248]
## Ask your Question

viewpager on android  slide to next page when scroll offset up to about 60% , how to change the default offset? i hope page move to next page when i scroll 30% offset on android

**Comment by troZee** [comment]
You can to do this on JS side inside the method `onPageScroll`. Then you need to calculate 30% of width and if this condition is fulfilled, you need to call https://github.com/callstack/react-native-viewpager/blob/master/example/ViewPagerExample.js#L116

Bc I can see, it is possible on native side using some kind of workarounds https://stackoverflow.com/questions/17318625/make-viewpager-snap-with-shorter-drag/17322361#17322361

https://stackoverflow.com/questions/11731878/is-there-a-way-to-customize-the-threshold-for-viewpager-scrolling/11734445#11734445

So you can use both approaches :D

**Comment by lishuo0710** [comment]
@troZee the link is 404 https://github.com/callstack/react-native-viewpager/blob/master/example/ViewPagerExample.js#L116,i will
try to handle that  on native side,thanks

**Comment by avidhaus-adeel** [comment]
@lishuo0710 are you able to handle this on native side? If so, can you please share example.
Thank You

**Comment by lishuo0710** [comment]
> @lishuo0710 are you able to handle this on native side? If so, can you please share example.
> Thank You

 try this : https://stackoverflow.com/questions/17318625/make-viewpager-snap-with-shorter-drag/17322361#17322361

**Comment by avidhaus-adeel** [comment]
> > @lishuo0710 are you able to handle this on native side? If so, can you please share example.
> > Thank You
> 
> try this : https://stackoverflow.com/questions/17318625/make-viewpager-snap-with-shorter-drag/17322361#17322361

@lishuo0710 can you please explain this. It is handled on native side and I don't have experience on native android coding

**Comment by lishuo0710** [comment]
> > > @lishuo0710 are you able to handle this on native side? If so, can you please share example.
> > > Thank You
> > 
> > 
> > try this : https://stackoverflow.com/questions/17318625/make-viewpager-snap-with-shorter-drag/17322361#17322361
> 
> @lishuo0710 can you please explain this. It is handled on native side and I don't have experience on native android coding

you can edit the onPageScrolled method(the 0.7 and 0.3 is offset ) in node_modules\@react-native-community\viewpager\android\src\main\java\com\reactnativecommunity\viewpager\ReactViewPager.java
```  
public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
      // mEventDispatcher.dispatchEvent(
      //     new PageScrollEvent(getId(), position, positionOffset));
      if(positionOffset < mLastPositionOffset && positionOffset < 0.7) {
          setCurrentItem(position,true);
          } else if(positionOffset > mLastPositionOffset && positionOffset > 0.3) {
          setCurrentItem(position+1,true);
      }
      mLastPositionOffset = positionOffset;
    }
```

**Comment by avidhaus-adeel** [comment]
> > > > @lishuo0710 are you able to handle this on native side? If so, can you please share example.
> > > > Thank You
> > > 
> > > 
> > > try this : https://stackoverflow.com/questions/17318625/make-viewpager-snap-with-shorter-drag/17322361#17322361
> > 
> > 
> > @lishuo0710 can you please explain this. It is handled on native side and I don't have experience on native android coding
> 
> you can edit the onPageScrolled method(the 0.7 and 0.3 is offset ) in node_modules@react-native-community\viewpager\android\src\main\java\com\reactnativecommunity\viewpager\ReactViewPager.java
> 
> ```
> public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
>       // mEventDispatcher.dispatchEvent(
>       //     new PageScrollEvent(getId(), position, positionOffset));
>       if(positionOffset < mLastPositionOffset && positionOffset < 0.7) {
>           setCurrentItem(position,true);
>           } else if(positionOffset > mLastPositionOffset && positionOffset > 0.3) {
>           setCurrentItem(position+1,true);
>       }
>       mLastPositionOffset = positionOffset;
>     }
> ```

where did you define mLastPositionOffset ?

**Comment by lishuo0710** [comment]
> > > > > @lishuo0710 are you able to handle this on native side? If so, can you please share example.
> > > > > Thank You
> > > > 
> > > > 
> > > > try this : https://stackoverflow.com/questions/17318625/make-viewpager-snap-with-shorter-drag/17322361#17322361
> > > 
> > > 
> > > @lishuo0710 can you please explain this. It is handled on native side and I don't have experience on native android coding
> > 
> > 
> > you can edit the onPageScrolled method(the 0.7 and 0.3 is offset ) in node_modules@react-native-community\viewpager\android\src\main\java\com\reactnativecommunity\viewpager\ReactViewPager.java
> > ```
> > public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
> >       // mEventDispatcher.dispatchEvent(
> >       //     new PageScrollEvent(getId(), position, positionOffset));
> >       if(positionOffset < mLastPositionOffset && positionOffset < 0.7) {
> >           setCurrentItem(position,true);
> >           } else if(positionOffset > mLastPositionOffset && positionOffset > 0.3) {
> >           setCurrentItem(position+1,true);
> >       }
> >       mLastPositionOffset = positionOffset;
> >     }
> > ```
> 
> where did you define mLastPositionOffset ?
 ```
private float mLastPositionOffset = 0f;
public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
      // mEventDispatcher.dispatchEvent(
      //     new PageScrollEvent(getId(), position, positionOffset));
      if(positionOffset < mLastPositionOffset && positionOffset < 0.7) {
          setCurrentItem(position,true);
          } else if(positionOffset > mLastPositionOffset && positionOffset > 0.3) {
          setCurrentItem(position+1,true);
      }
      mLastPositionOffset = positionOffset;
}
```
