### ISSUE TITLE
Lack of documentation for onPageSelected 

### ISSUE THREAD

**Issue by goleary** [callstack/react-native-viewpager#280]
I just spent 20 minutes trying to figure out how to use this callback because of the lack of explanation on how to access the index of the selected page.

after digging through this repo I figured this out:
```js
  onPageSelected = e => {
    // You can access it by e.nativeEvent.position
  };
```
Because of another issue (#33) that was opened due to the lack of documentation of this prop.

**Comment by MateWW** [comment]
We linked example in `README` should be fine now.

**Comment by Brysonmk1984** [comment]
@MateWW I also spent about 20 minutes just trying to figure out how to access the existing page. I didn't see a linked example in README besides the "advanced usage", but even that didn't seem to use "e.nativeEvent.position". I think this functionality is so common, it should be made pretty clear in the docs. It would be easy to just mention how to access the current page in the section that explains "onPageSelected".

**Comment by daamsie** [comment]
Also wasted far too long working this out. Eventually discovered how to do it from this issue thread. Thanks @Brysonmk1984 

Agreed it's a very common need and it should be made more clear.
