### ISSUE TITLE
How to determine page number in an event?

### ISSUE THREAD

**Issue by IPWright83** [callstack/react-native-viewpager#287]
## Ask your Question
How do I obtain the page number scrolled to in the events (e.g. the onPageScroll event). I can't seem to find anything in the synthetic event to work out which page number I'm on.

**Comment by jefersonvinicius** [comment]
You already tested ```onPageSelected``` event?

```js
...
onPageSelected={(event) => console.log(event.nativeEvent.position)}
...
```

**Comment by IPWright83** [comment]
@jefersonvinicius thanks, I'll take another look. I tried to dig into some of the properties, I maybe just missed it not knowing where to look.

**Comment by IPWright83** [comment]
Ok, so the confusion came around the fact that if you log `event` then expand `nativeEvent` in the debugger it's always `null`. But it is infact populated if you log it at the time of the event.

Thanks :)
