### ISSUE TITLE
How to handle the landscape and portrait orientation design?

### ISSUE THREAD

**Issue by sankar9659** [callstack/react-native-viewpager#296]
Hi i' have used react-native swiper package for swiping functionality.
And in that package, i'm not able to handle the landscape and portrait orientation design,
So i have tried this view pager package.
Can i handle the screen design dynamically when change the screen orientation?
Also is there any possible to initialize the initial screen, (I have 5 data in an array, and i want to show the 3rd index data)?
Can anyone share the sample code for this?
Thanks in advance.

**Comment by troZee** [comment]
Hello 👋 
i am glad, you are using viewpager in your project. 

> Hi i' have used react-native swiper package for swiping functionality.
> And in that package, i'm not able to handle the landscape and portrait orientation design
> Can i handle the screen design dynamically when change the screen orientation?

What do you mean by that ? Could you describe use case ?
Library supports orientation changes.

> Also is there any possible to initialize the initial screen, (I have 5 data in an array, and i want to show the 3rd index data)?

Yes it is possible. More here https://github.com/callstack/react-native-viewpager/tree/master/example

**Comment by sankar9659** [comment]
@troZee  Thanks for the reply.
I mean i need to handle the swiper design in both orientation (landscape and portaid) i m facing issue in react-native swiper like below image. image not appearing properly. (2 images showing at a same time sometimes)
![Screenshot_1614749730](https://user-images.githubusercontent.com/58698022/109757855-9e2cf700-7c10-11eb-8bfa-84ce3696fee0.png)
![Screenshot_1614749720](https://user-images.githubusercontent.com/58698022/109757868-a1c07e00-7c10-11eb-873b-9efa19d5db19.png)


So that i m trying the viewpager package. Does it work in portraid and landscape mode?

**Comment by troZee** [comment]
> So that i m trying the viewpager package. Does it work in portraid and landscape mode?

![WhatsApp Image 2021-03-03 at 08 06 36](https://user-images.githubusercontent.com/12766071/109767347-b5131f80-7bf7-11eb-8742-6215c05d747d.jpeg)

Yes it works for both ios and android

**Comment by sankar9659** [comment]
Working good. Thanks @troZee
