### ISSUE TITLE
TypeError: null is not an object (evaluating '_ref.props')

### ISSUE THREAD

**Issue by sachinkaria** [callstack/react-native-viewpager#300]
## Environment

```
iOS 14.3
React-Native: 62.2.0
react-native-community/viewpager: ^5.0.11
```

## Description

I am rendering a simple ViewPager component that is throwing this error on the iOS simulator.

```TypeError: null is not an object (evaluating '_ref.props')```

## Reproducible Demo

```
const RenderViewPage = () => {
let pager = React.createRef();
let activeSlide = 0;
  return (
          <ViewPager
            requestAnimationFrame={() => pager.current?.setPage(activeSlide)}
            ref={pager}
            onPageSelected={(e) => setActiveSlide(e.nativeEvent.position)}
            orientation="vertical"
            style={{
              height: Metrics.screenHeight,
              width: Metrics.screenWidth
            }}
            initialPage={0}>
         <View></View>
  </ViewPager>
  )
}
```

**Comment by NathanBeesley** [comment]
Are you able to use hooks? Does something like this work for you? Your above code works for me besides the prop requestAnimationFrame doesn't exist on type ViewPager.

const viewPagerRef = useRef<ViewPager>(null)

    <ViewPager
        ref={viewPagerRef}
        initialPage={0}
        style={{ flex: 1 }}
        onPageSelected={setCurrentStep} />

**Comment by NathanBeesley** [comment]
Where are you seeing requestAnimationFrame is a valid prop? Im using typescript and I get the following error -> 'requestAnimationFrame' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ViewPager> ...

Have you tried removing that prop? Otherwise the way you are creating the ref seems to work.

**Comment by troZee** [comment]
Hello, 
Solution you can find here: https://github.com/callstack/react-native-viewpager/tree/master/example

**Comment by sharifme04** [comment]
i am getting same error, 
` ERROR  TypeError: null is not an object (evaluating '_ref.props')

This error is located at:
    in ViewPager (created by ViewPager)
    in ViewPager (created by IndicatorViewPager)
    in RCTView (created by View)
    in View (created by IndicatorViewPager)
    in IndicatorViewPager (created by DocumentDetailsScreen)
    in RCTView (created by View)
`

**Comment by fukemy** [comment]
why i still meet this crash??

**Comment by arihantop** [comment]
> why i still meet this crash??

try adding if(!child){ return} in utils.tsx file of this library in node_modules
